services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-rabbitmq}
    volumes:
      - ./data/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./data/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./data/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./data/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  data:
    driver: local
