services:
    mongodb:
        image: mongodb/mongodb-community-server:latest
        container_name: mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongodb:/data/db
        environment:
            ZZMONGO_INITDB_ROOT_USERNAME: admin
            ZZMONGO_INITDB_ROOT_PASSWORD: admin

volumes:
    mongodb:
        external: true
